# Overview

The Python programming language was developed in the early 1990s by the Dutch Programmer Guido Van Rossum. It represents a high-level, interpreted, interactive and object-oriented language which is designed to be fun and easy to use. 

Since this time, the popularity for Python has grown considerably to the point where it is now one of the 2 most widely used programming languages adopted within the Machine Learning and Data Science communities. The other being there statistical programming language R

Python is **Interpreted** and **Interactive**

-  Code is processed at runtime 
-  There is no need to compile before execution (similar to Matlab)
-  Thus code can be run line by line (similar to Matlab)

Generally the code is designed with simple structure and clear syntax in order to make it easy to learn. Python is highly portable, the code written on one operating system can be simply ported to another. Python is compatible with Unix, Mac OS, Windows, Android, IOS platforms. It is open source, and supported by a wide community, which supports a wide range of well documented and advanced packages for numerical and image analysis. A selection of those that will be particularly useful for this book are:


- **```NumPy```** is the fundamental package for scientific computing in Python and it is used for working with multidimensional arrays. Link to the documentation for NumPy: https://numpy.org/doc/stable/
- **```Scikit-learn```** is an open source machine learning library that supports supervised and unsupervised learning. It also provides various tools for model fitting, data preprocessing, model selection and evaluation, and many other utilities. Link to the documentation for Scikit-learn: https://scikit-learn.org/stable/user_guide.html![image.png](attachment:image.png)
- **```Matplotlib```** is a comprehensive library for creating static, animated, and interactive visualizations in Python. Link to the documentation for Matplotlib: https://matplotlib.org/users/index.html
- **```Pandas```** is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language. Link to the documentation for Pandas: https://pandas.pydata.org/docs/user_guide/index.html
- **```NiBabel```**  provides read and write access to some common medical and neuroimaging file formats, including: ANALYZE (plain, SPM99, SPM2 and later), GIFTI, NIfTI1, NIfTI2, CIFTI-2, MINC1, MINC2, AFNI BRIK/HEAD, MGH and ECAT as well as Philips PAR/REC. Link to the documentation for NiBabel:  https://nipy.org/nibabel/manual.html#manual

# Basics of Python

Jupyter Notebooks have two different keyboard input modes:

- **Command mode** binds the keyboard to notebook level actions. Indicated by a grey cell border with a blue left margin.
- **Edit mode** when you’re typing in a cell. Indicated by a green cell border

Some useful **shortcuts** to interact with the Jupyter Notebook:
- ``` Shift + Enter``` run the current cell
- ``` Ctrl + S ``` save notebook
- ``` Ctrl + Z ``` undo

In Command Mode:
- ``` A ``` insert cell above
- ``` B ``` insert cell below
- ``` X ``` cut selected cells
- ``` C ``` copy selected cells
- ``` V ``` paste cells below


Note that the shortcuts are for ```Windows``` and ```Linux``` users. For the ```Mac``` users, they’re different buttons for ```Ctrl```, ```Shift```, and ```Alt```:
- ``` Ctrl + S ```: command key ```⌘```
- ``` Shift ```: Shift ```⇧```
- ``` Alt ```: option ```⌥```


The first part of this notebook will focus on the basics of Python, covering simple variables and tuples, lists strings and math operators, conditions and functions.

### 1) Structuring your code

Python uses indentation instead of braces to structure its programs and scripts into blocks.  All code within a block must be horizontally aligned such that each line starts equidistant from the left.

A code blocks is a piece of Python program text that can be executed as a unit. A very common example of code block is a ```for``` loop that is traditionally used when you have a block of code which you want to repeat a fixed number of times.  The below section of code provides an example with two ```for``` loops.  Note that you are not, at this time, expected to understand all the specific syntactic elements. Simply observe how each ``` for``` statement the code moves further to the left.

In [ ]:
#the first code block
myfirstlist=[10,20,30,40]
mysecondlist=[1,2,3,4,5]

for tens in myfirstlist:
    #the second code block (a for loop over a list of integers)
    print('Entering second code block') 
    for units in mysecondlist:
        #the third code block (a for loop over a second list of integers)
        new_number=tens+units
        print('Output of third code block; The new number is',new_number)


Entering second code block
Output of third code block; The new number is 11
Output of third code block; The new number is 12
Output of third code block; The new number is 13
Output of third code block; The new number is 14
Output of third code block; The new number is 15
Entering second code block
Output of third code block; The new number is 21
Output of third code block; The new number is 22
Output of third code block; The new number is 23
Output of third code block; The new number is 24
Output of third code block; The new number is 25
Entering second code block
Output of third code block; The new number is 31
Output of third code block; The new number is 32
Output of third code block; The new number is 33
Output of third code block; The new number is 34
Output of third code block; The new number is 35
Entering second code block
Output of third code block; The new number is 41
Output of third code block; The new number is 42
Output of third code block; The new number is 43
Output of 

### 2) Hello World
The simplest function in Python is the print function. To print a statement simply type.

In [ ]:
print("Hello World")

Hello World


**Formatted output**

In some cases we would like to print statements with formatted output. To this end, we can use the ```format``` method. 

Using this formulation it is also possible to cast data types and truncate floats. The general syntax for a format placeholder is:

```[argument]:[width][.precision]type```


In [ ]:
# Examples of the print function with multiple formats
print('{} {}'.format('one', 'two'))
print('{} {}'.format(1,2))
print('Pi= {}'.format(3.14159))
print('Pi= {0:8.2f}'.format(3.14159))

one two
1 2
Pi= 3.14159
Pi=     3.14


### 3) Commenting
It is always important to comment code such that others can read and use it. In Python the way of commenting code is to use the the hash mark ```#``` before your desired comment and


In [11]:
# this is a  code comment


### 4) Basic data types

Like most languages, Python has a number of basic types including integers, floats, Booleans, and strings. These data types behave in ways that look like from other programming languages.

**Numbers:** Integers and floats 

**Booleans:** Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols:
-	```and``` for boolean AND
-	```or``` for boolean OR
-	``` not ``` for boolean NOT

**Strings:** Strings are defined either with a single quote ```''``` or a double quotes ```""``` 

In [1]:
# Example of assigning to a variable an integer value is:
myint = 9
print('example integer is ', myint)

# Examples of float declarations are:
myfloat1=9.3
myfloat2=float(9)
print('example integer is ', myfloat1)
print('casting an integer as a float results in', myfloat2)

# Examples of booleans declarations are:
mybool1 = True
mybool2 = False
print('example booleans are ', mybool1, ' and ', mybool2)

# Strings are defined either with a single quote or a double quotes e.g. 
string1="hello world"
string2='hello world'
print (string1)
print(string2)
print('testing if string1 and string2 are equal:', string1==string2)

# String objects have a bunch of useful methods. For example:
s = "hello"
# Capitalize a string
print(s.capitalize())  
# Convert a string to uppercase
print(s.upper())    
# Right-justify a string, padding with spaces   
print(s.rjust(7))  
# Center a string, padding with spaces    
print(s.center(7))     
 # Replace all instances of one substring with another
print(s.replace('l', '(ell)')) 
# Strip leading and trailing whitespace
print('  world '.strip())



example integer is  9
example integer is  9.3
casting an integer as a float results in 9.0
example booleans are  True  and  False
hello world
hello world
testing if string1 and string2 are equal: True
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### 5) Operators
The basic math operators are:
- addition (```+```)
- subtraction (```-```)
- multiplication (```*```)
- division (```/``` or ```//```)
- modulus (```%```)
- power (```**```)



In [2]:
# Examples of simple math operations:
print('addition:', 2+3)
print('subtraction:', 2-3)
print('multiplication:', 2*3)
print('division:', 2/3)
# The modulus operator (```%```) returns the integer remainder following division:
a=9
b=5
print('the remainder following division of {} by {} is {}'.format(a, b, a%b))
# Using ```*``` twice (```**```) results in the power operator
a=2
b=4
print('{} to the power {} is {}'.format(a, b, a**b))

addition: 5
subtraction: -1
multiplication: 6
division: 0.6666666666666666
the remainder following division of 9 by 5 is 4
2 to the power 4 is 16


### 6) Conditions

Conditions containing boolean operators ``` == > < ``` are formatted as:

In [3]:
a=10
print(a==10)
print(a<12)
print(a>20)

# Two conditional statements can be considered concurrent with ```and,or, and is``` statements
a=10
b=12
print(a is b)
print(a< 15 and b > 10)
print (a < 15 or b < 10)

# Using "not" before a boolean expression inverts it:
print(not a is b)

True
True
False
False
True
True
True


### Exercise: Variables, Operators and Conditions

Ex 1. Playing with the print function and string formatting 

In [ ]:
# Complete Ex 1 below; responding below each comment block

# Q1. Define variables and print them
#e.g. a=8; b=7; teststr='Hello World'

# Q2. Practice print statements e.g. print('hello world')


# Q3. Try printing the variable teststr (what if you change to double quotes)


# Q4. Try adding the variable 'a' to variable 'teststr' within a print statement 


In [5]:
# SOLUTIONS EX 1.

# Q1. Define variables and print them
a=8 
b=7
teststr='Hello World'
print(teststr)
print("a={} and b={}" .format(a, b))


# Q2. Practice print statements e.g. print('hello world')
print('hello world')

# Q3. Try printing the variable teststr (what if you change to double quotes)
teststr="Hello World"
print(teststr)

# Q4. Try adding the variable 'a' to variable 'teststr' within a print statement 
print('{} {}'.format(teststr,a))
print(teststr +' '+ str(a))
print(f"{teststr} {a}")

Hello World
a=8 and b=7
hello world
Hello World
Hello World 8
Hello World 8
Hello World 8


Ex 2. Try some simple operations

In [ ]:
# Complete Ex 2 below; responding below each comment 

# Q1. Attempt simple math operations, print the output (Hint - uncomment and complete)

#print(' a+b = ', )
#print(' a -b = ', )
#print(' a*b = ', )
#print(' a/b = ', )

# Q2. Combinations of math operators try combining math operators e.g. a*a+b - a/b 


# Q3. What happens through the addition of brackets e.g. a*(a+b - a/b) or (a*a+b - a)/b 


In [13]:
# SOLUTIONS EX 2.

# Q1. Attempt simple math operations, print the output (Hint - uncomment and complete)
a=8 
b=7

print(' a+b = {}'.format(a+b))
print(' a-b = {}'.format(a-b))
print(' a*b = {}'.format(a*b))
print(' a/b = {:.2f}'.format(a/b))

# Q2. Combinations of math operators try combining math operators e.g. a*a+b - a/b 
print(' a*a+b - a/b = {:.2f}' . format(a*a+b-a/b))

# Q3 what happens through the addition of brackets e.g. a*(a+b - a/b) or (a*a+b - a)/b 
print(' a*(a+b - a/b) =  {:.2f}' . format(a*(a+b - a/b)))
print(' (a*a+b - a)/b =  {:.2f}' .format((a*a+b -a)/b))


 a+b = 15
 a-b = 1
 a*b = 56
 a/b = 1.14
 a*a+b - a/b = 69.86
 a*(a+b - a/b) =  110.86
 (a*a+b - a)/b =  9.00


Ex 3. Experiment with Conditions

In [ ]:
# Complete Ex 3 below; responding below each comment 

# Q1. define variables 

a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 complete and evaluate the following conditional statements
print('a==b',)
print('2*a==b',)
print('a>b',)
print('a<b',)
print('a is b',)
print('2*a is b',)

# Q3. Combine statements using and/or statements e.g. 'a == b or b> a' and print out


# Q4. Try inverting your previous statements with a not

In [14]:
# SOLUTIONS EX 3.

# Q1. define variables 

a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 complete and evaluate the following conditional statements
print('a==b',a==b)
print('2*a==b',2*a==b)
print('a>b',a>b)
print('a<b',a<b)
print('a is b',a is b)
print('2*a is b',2*a is b)

# Q3. Combine statements using and/or statements e.g. 'a == b or b> a' and print out
print(a==b or b>a)

# Q4. Try inverting your previous statements with a not
print(not(a==b or b>a))


a==b False
2*a==b True
a>b False
a<b True
a is b False
2*a is b True
True
False


### 7) Lists

A list is an ordered collection of objects. List elements don't have to be of the same type but can be an arbitrary mixture of numbers, strings, or other types of objects. Lists can contain other lists as sub-lists. Examples of lists:

In [1]:
emptylist=[] # An empty list
integerlist=[1,2,3,4,5,6] #A list of integers
stringlist=['string1', 'string2', 'string3'] #A list of strings
mixedlist=[10, "some string", 4.2, 2, 'some other string'] #A list of mixed data types
# a nested list  - note sublists are not same lengths
nestedlist=[['dog','cat','pig'], [1,2,3 ,4], [10, "some string", 4.2, 2, 'some other string'] ]

**Indexing sequential data types**

In a list is possible to index and slice different elements or groups of elements as follows:

** <font color='red'> NOTE in python all array like objects are indexed from 0  </font>  **

In [5]:
teststr='Hello World'
print('the third element of the integer list', integerlist[2])
print('the fourth element of the mixed list', mixedlist[3])
print('the seventh element of the string', teststr[6])

# note slice indexing takes all elements upto but not including the last index 
print('the middle two elements of the integer list', integerlist[2:4])
#slicing from the beginning to element 5
print('the middle two elements of the integer list', integerlist[:5])
#slicing from element 5 to the end
print('the middle two elements of the integer list', integerlist[4:])
#slicing from element 5 to one from the end
print('the middle two elements of the integer list', integerlist[4:-1])
# Indexing can also be done in reverse:
print('the last element of the integer list', integerlist[-1])


the third element of the integer list 3
the fourth element of the mixed list 2
the seventh element of the string W
the middle two elements of the integer list [3, 4]
the middle two elements of the integer list [1, 2, 3, 4, 5]
the middle two elements of the integer list [5, 6]
the middle two elements of the integer list [5]
the last element of the integer list 6


**Assignment and Mutation**

It is possible to increase the length of a list using ```append()```

In [ ]:
integerlist.append(7)
print('new integer list', integerlist)

Incidentally the lengths of strings and lists can be determined using ```len()```:

In [ ]:
print('the length of the new integer list is', len(integerlist))
print('the length of the teststr is', len(teststr))

Lists can be added together like strings:

In [ ]:
print(integerlist+stringlist)

Items of lists can be swapped out for new ones:

### Exercise: Lists

Ex 1. Lists:

    - Create an list of integers
    - Estimate the length of the list; print it out
    - Index the list at different points along its length
    - Take a slice of a subset of elements from the list
    - Append the list with a new item of a different type

In [ ]:
#Complete responses to Ex1 here, e.g. mylist=[1,2,3,4,5]

# index elements at different lengths along the list 

# index the last element of your list

# slice

# append

In [15]:
# SOLUTIONS EX 1.

mylist=[1,2,3,4,5]

# index elements at different lengths along the list 

print(mylist[0],mylist[1],mylist[3])

# index the last element of your list

print(mylist[-1])

# slice

print(mylist[1:3])

# append

mylist.append(43110)

1 2 4
5
[2, 3]


Ex 2. Operations on sequential data types

    - Concatenate two strings, and two lists 
    - Concatenate 10 copies of each string

In [ ]:
#Complete responses to Ex2 below

string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Important - Never name your variables after data types i.e. str='mystring', list=['some', 'list'] should never be used 

# Q1 Concatenate two strings, and two lists 

# Q2  Concatenate 10 copies of each string


In [16]:
# SOLUTIONS EX 2.

string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Q1 Concatenate two strings, and two lists 

print(string1+string2)
print(list1+list2)

# Q2  Concatenate 10 copies of each string

print(string1*10)

HelloWorld
['Hello', 'World', "I'm", 'ready', 'toPython']
HelloHelloHelloHelloHelloHelloHelloHelloHelloHello


<font color='red'>**TODO:** We should see how to better highlight these sections from  the introductory ones</font> 

### 8) Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 



**Arrays** 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [9]:
import numpy as np

# Create a rank 1 array
a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
# Change an element of the array
a[0] = 5                  
print(a)                 
# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:


In [10]:
import numpy as np

# Create a 2x2 array of all zeros
a = np.zeros((2,2))   
print(a)             

# Create a 1x2 array of all ones
b = np.ones((1,2))    
print(b)              

# Create a 2x2 constant array
c = np.full((2,2), 7)  
print(c)              

# Create a 2x2 identity matrix
d = np.eye(2)         
print(d)              

# Create a 2x2 array filled with random values
e = np.random.random((2,2))  
print(e)                    

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.5746982  0.03840111]
 [0.84676011 0.34556737]]


**Array indexing**

Numpy offers several ways to index into arrays.

Similar to lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [21]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2. 
b = a[:2, 1:3]
print(b)

# Note that slice of an array is a way of viewing the data of the array and that means that means that 
# the data of both objects is shared. For this reason if we modified 'b' it will also modify the original array.  
print(a[0, 1])   
b[0, 0] = 77     
print(a[0, 1])   

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank compared to the original array. 



In [16]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Boolean array indexing**

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.



In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# Find the elements of a that are bigger than 2; this returns a numpy array of Booleans of the same 
# shape as a, where each slot of bool_idx tells whether that element of a is > 2.
bool_idx = (a > 2)   

print(bool_idx)     

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  

# We can do all of the above in a single concise statement:
print(a[a > 2])     

### Exercise: Numpy

In [ ]:
Ex 1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array. 
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [22]:
# Complete responses to Ex1 here, e.g. mylist=[12.23, 13.32, 100, 36.32]
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


Ex2: Write a NumPy program to create a null vector of size 10 and update its sixth value to 11

Expected Output: 
```
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]```

In [23]:
# Complete responses to Ex2 here
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


Ex3: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:
```
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]```

In [24]:
# Complete responses to Ex3 here
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Ex4: Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

Checkerboard pattern:
```
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```




In [25]:
# Complete responses to Ex4 here
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Ex5: Write a NumPy program to append values to the end of an array

Original array: 
```[10, 20, 30]```

After append values to the end of the array:
```[10 20 30 40 50 60 70 80 90]```

In [26]:
# Complete responses to Ex5 here
import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


Ex6: Write a NumPy program to find common values between two arrays. 

Array1: ```[ 0 10 20 40 60]```

Array2: ```[10, 30, 40]```

Common values between two arrays:``` [10 40]```

In [27]:
# Complete responses to Ex6 here
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


### 9) Conditional (if) statements

Similar to the steps of a decision trees, conditional statements can be formulated in Python as: 

```if condition:
    statement
    statement```  

The conditional statement must evaluate to a boolean (```True/False```)  but otherwise there are few constraints. The  decision tree below can be transcript as follows:
<img src="HF_decision_tree.png" height="400">


In [37]:
LVEF = int(input('Please introduce value for LVEF: '))

if LVEF > 50:
    print('HFpEF')
else:
    if LVEF < 40:
        print('HFrEF')
    else:
        print('HFmEF')

HFrEF


All forms of conditional statement (described in (6)) may be used, including use or ```is/and/or``` statements e.g. 

In [ ]:
a=10
b=12

if a< 15 and b > 10:
    print('run the following block of code')


The "in" operator can also be used to check if a specified object exists within an iterable object container, such as a list:

In [ ]:
name = "John"
if name in ["John", "Dave"]:
    print("The person's name is either John or Dave.")

Series of if statements can be combined within if else statements i.e.

In [ ]:
BMI=20

if BMI <= 18.5: # >= greater than or equal to
    print('This person is underweight')
elif BMI > 18.5 and BMI <=25.0:
    print('This person has normal weight')
elif BMI > 25.0 and BMI <=30.0 :
    print('This person is overweight')
else:
    print('This person is obese')


EXERCISES:

Ex1) try changing the BMI and exploring the response

Ex2) Try reproducing the following decision tree and play with the input values to verify the final decision:

<img src="IHCA_decision_tree.png" height="400">

Decision tree from [1]
[1] Li, Hong, et al. "Decision tree model for predicting in‐hospital cardiac arrest among patients admitted with acute coronary syndrome." Clinical cardiology 42.11 (2019): 1087-1093.

In [61]:
# complete the answer the answer to EX 2 here:
ViEWS = int(input('Please introduce value for ViEWS: '))
arrhythmia = int(input('Please introduce fatal arrhythmia status (yes = 1, no = 0):'))
diabetes = int(input('Please introduce diabetes status (yes = 1, no = 0):'))
Killip = int(input('Please introduce Killip class (class І = 1, II = 2, III = 3, IV = 4):'))
BUN = int(input('Please introduce value for blood urea nitrogen (BUN):'))
cTnI = int(input('Please introduce value for cardiac troponin I (cTnI):'))

if ViEWS < 5:
    if arrhythmia:
        if Killip > 2:
            if cTnI >= 28:
                print('High (70%‐100%)')
            else:
                if BUN < 7.9:
                    print('Moderate (40%‐69%)')
                else:
                    print('Low (<40%)')  
        else:
            print('Low (<40%)')

    else:
        print('Low (<40%)')
else:
    if diabetes:
        print('High (70%‐100%)')
    else:
        if age < 64:
            print('Low (<40%)')
        else:
            print('Moderate (40%‐69%)')


Please introduce value for ViEWS: 6
Please introduce fatal arrhythmia status (yes = 1, no = 0):1
Please introduce diabetes status (yes = 1, no = 0):1
Please introduce Killip class (class І = 1, II = 2, III = 3, IV = 4):1
Please introduce value for blood urea nitrogen (BUN):5
Please introduce value for cardiac troponin I (cTnI):2
High (70%‐100%)


### 10) ```For``` statements

For loops iterate over a given sequence, for example as given by a list:

In [ ]:
mylist=[10,20,30,40,50]

for item in mylist:
    print(item)

For numeric ranges, python the provides function ```range(start,end,increment)``` which provides an inline definition e.g. 

In [ ]:
for item in range(0,10,2):
    print(item)

EXERCISE, try changing the range and adding different increments, start and end points)



It is possible to have  ```for ``` loops nested within each other

In [ ]:
#the first code block
myfirstlist=[10,20,30,40]
mysecondlist=[1,2,3,4,5]

for tens in myfirstlist:
    #the second code block (a for loop over a list of integers)
    for units in mysecondlist:
        #the third code block (a for loop over a second list of integers)
        new_number=tens+units
        #print('Output of third code block; The new number is',new_number)

**enumerate**

In some cases you might need to use the both the list item and the index of the loop. In such circumstances it is possible to use the enumerate function

In [ ]:
mylist=['one','two','three','four','five']

for index,item in enumerate(mylist):
    print(index,item)

### 11) Functions

Functions allow compact structuring of sections of code that are intended to be used more than once in a progam (or indeed multiple programs). 

A function in Python is defined by a ```def``` statement. In pseudocode, the general syntax looks like this:

``` 
def myfunction(arg1,arg2,arg3): # function definition (with optional) input arguments; 
    
    body of code to be repeated
    
    return someval1, someval2 
    ```

Note the colon at the end of the function header, and the use of indentation within the body of the function. Inside the function are lines of code that would otherwise by repeated multiple times in the program. The function then returns (optionally returning output arguments). For simple functions the function can be returned in one line e.g.

In [33]:
# define function
def sum(x,y):
    return x+y # here as the function is simple it can be returned in one line

# apply function

a=5
b=10

print('sum of {} and {} is {}'.format(a,b,sum(a,b)))

sum of 5 and 10 is 15


It is also possible to supply optional input arguments with default values e.g.

In [ ]:
# this function can thus return a sum of 2 or 3 arguments
def sum2(x,y,z=0):
    return x+y+z 

# apply function

a=5
b=10
c=20

print('sum of {} and {} is {}'.format(a,b,sum2(a,b)))
print('sum of {},{} and {} is {}'.format(a,b,c, sum2(a,b,c)))

Or specify which exact optional arguments will be required the use through use of keywords (referencing the specific argument name in the function call):

In [ ]:
def sumsub(x, y, z1=0, z2=0):
    return x - y + z1 - z2

# apply function

a=5
b=10
c=20
d=30

print(sumsub(12,4))
print(sumsub(42,15,z2=10))
print(sumsub(42,15,z1=20, z2=10))

### Exercises - loops and functions:

Ex. 1 Write a function that takes systolic and diastolic blood pressure as input and prints in which category is the subject based on the table below:
<img src="BloodPressure.png" height="400">

In [41]:
# Blood pressure function
def blood_pressure(sytolic_bp, diastolic_bp):
  # Write conditions, use print to show the category assigned 
  print('TODO')

sytolic_bp = int(input('Please introduce value for systolic blood pressure: '))
diastolic_bp = int(input('Please introduce value for diastolic blood pressure: '))
blood_pressure(sytolic_bp, diastolic_bp)

Please introduce value for systolic blood pressure: 121
Please introduce value for diastolic blood pressure: 77
TODO


In [62]:
# complete the answer the answer to EX 1 here:
def blood_pressure(sytolic_bp, diastolic_bp):
    # Write conditions, use print to show the category assigned 
    if (sytolic_bp < 120 and diastolic_bp < 80):
        print('Normal')
    elif (120 < sytolic_bp <= 129 and diastolic_bp < 80):
        print('Elevated')
    elif (130 <= sytolic_bp <= 139 or 80 <= diastolic_bp < 89):
        print('Hypertension stage 1')
    elif (sytolic_bp > 180 or diastolic_bp > 120):
        print('Consult your doctor immediately')
    elif (140 <= sytolic_bp < 180 or 90 <= diastolic_bp < 120):
        print('Hypertension stage 2')

blood_pressure(sytolic_bp, diastolic_bp)

Hypertension stage 1


Ex 2. Write a list that simulates 10 subjects, and and for each specify their systolic and diastolic blood pressure. Use a for loop and the function in exercise 1 to display the category for each subject

In [75]:
# complete the answer the answer to EX 2 here:
import random
for i in np.arange(10):
    sytolic_bp = random.randint(90, 200)
    diastolic_bp = random.randint(60, 130)
    print('Subject {} -> Sytolic bp = {} and diastolic bp = {}'.format(i, sytolic_bp, diastolic_bp))
    blood_pressure(sytolic_bp, diastolic_bp)

Subject 0 -> Sytolic bp = 177 and diastolic bp = 65
Hypertension stage 2
Subject 1 -> Sytolic bp = 125 and diastolic bp = 95
Hypertension stage 2
Subject 2 -> Sytolic bp = 94 and diastolic bp = 91
Hypertension stage 2
Subject 3 -> Sytolic bp = 106 and diastolic bp = 77
Normal
Subject 4 -> Sytolic bp = 125 and diastolic bp = 89
Subject 5 -> Sytolic bp = 158 and diastolic bp = 108
Hypertension stage 2
Subject 6 -> Sytolic bp = 108 and diastolic bp = 81
Hypertension stage 1
Subject 7 -> Sytolic bp = 142 and diastolic bp = 125
Consult your doctor immediately
Subject 8 -> Sytolic bp = 152 and diastolic bp = 75
Hypertension stage 2
Subject 9 -> Sytolic bp = 94 and diastolic bp = 82
Hypertension stage 1
